=== PZ-Wiki-Modding/pz-scripts-data/$schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Blocks Folder General Schema",
  "type": "object",
  "properties": {
    "version": { "type": ["number", "string"] },
    "name": { 
      "type": "string",
      "description": "The name of the block type." 
    },
    "description": { 
      "type": "string",
      "description": "A brief description of the block type."
    },
    "ID": { 
      "type": "object",
      "description": "Defines the ID properties for this block type.",
      "properties": {
        "parentsWithout": {
          "type": "array",
          "items": { "type": "string" },
          "description": "A list of block names that cannot be parents if this block has an ID."
        },
        "values": {
          "type": "array",
          "items": { "type": "string" },
          "description": "A list of allowed ID values for this block. If not given, any value is allowed."
        },
        "asType": {
          "type": "boolean",
          "description": "Specifies if the ID of the block should count as the block type. For example, components have specific definitions based on their ID. This means a script block needs to be defined with the name 'component <componentID>' as well as 'component' to cover all component types available with the 'values' attribute."
        }
      }
    },
    "shouldHaveParent": { 
      "type": "boolean",
      "description": "Indicates if the block should have a parent block."
    },
    "parents": {
      "type": "array",
      "items": { "type": "string" },
      "description": "A list of valid parent block types."
    },
    "needsChildren": {
      "type": "array",
      "items": { "type": "string" },
      "description": "A list of required child block types."
    },
    "parameters": { 
      "type": "array",
      "description": "A list of parameters available for this block type.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the parameter. (required)"
          },
          "#ref": {
            "type": "string",
            "description": "A reference to another block parameter."
          },
          "description": {
            "type": "string",
            "description": "A brief description of what the parameter does."
          },
          "allowedDuplicate": {
            "type": "boolean",
            "description": "Indicates whether the parameter can be duplicated."
          },
          "canBeEmpty": {
            "type": "boolean",
            "description": "Indicates whether the parameter can be empty."
          },
          "itemTypes": {
            "type": "array",
            "description": "Specifies the type of item the parameter is associated with (e.g., 'vehicle', 'item', etc.). Only for item scripts.",
            "items": { "type": "string" }
          },
          "parentsOnly": {
            "type": "array",
            "description": "A list of parent block types for which this parameter is applicable.",
            "items": { "type": "string" }
          },
          "required": {
            "type": "boolean",
            "description": "Indicates whether the parameter is required."
          },
          "default": {
            "type": ["string", "number", "boolean", "array", "object"],
            "description": "The default value for the parameter if not specified."
          },
          "type": {
            "type": "string",
            "description": "The data type of the parameter (e.g., 'string', 'int', 'float', 'boolean', etc.)."
          },
          "values": {
            "type": "array",
            "description": "A list of allowed values for the parameter.",
            "items": { "type": ["string", "number"] }
          },
          "deprecated": {
            "type": "boolean",
            "description": "Indicates whether the parameter is deprecated."
          }
        }
      }
    }
  }
}

=== PZ-Wiki-Modding/pz-scripts-data/data/blocks/model.json
{
    "version": 1.0,
    "$schema": "../../$schema.json",
    "name": "model",
    "description": "Defines a 3D model properties.",
    "shouldHaveParent": true,
    "parents": [
        "module",
        "vehicle",
        "part"
    ],
    "ID": {
        "parentsWithout": [
            "vehicle",
            "template"
        ]
    },
    "parameters": [
        {
            "name": "animationsMesh"
        },
        {
            "name": "boneWeight"
        },
        {
            "name": "ColorBlue"
        },
        {
            "name": "ColorGreen"
        },
        {
            "name": "ColorRed"
        },
        {
            "name": "cullFace"
        },
        {
            "name": "file"
        },
        {
            "name": "invertX"
        },
        {
            "name": "mesh"
        },
        {
            "name": "offset"
        },
        {
            "name": "postProcess"
        },
        {
            "name": "scale",
            "description": "Used to scale the model up or down.",
            "type": "float"
        },
        {
            "name": "shader"
        },
        {
            "name": "specialKeyRing"
        },
        {
            "name": "static"
        },
        {
            "name": "texture"
        },
        {
            "name": "undoCoreScale"
        }
    ]
}

=== PZ-Wiki-Modding/pz-scripts-data/data/blocks/option.json
{
    "version": 1.0,
    "$schema": "../../$schema.json",
    "name": "option",
    "description": "Defines a custom sandbox option for a mod.",
    "shouldHaveParent": false,
    "parents": [],
    "ID": {},
    "parameters": [
        {
            "name": "type",
            "type": "string",
            "description": "The type of the option.",
            "values": [
                "boolean",
                "integer",
                "double",
                "string",
                "enum"
            ],
            "required": true
        },
        {
            "name": "min",
            "type": "float"
        },
        {
            "name": "max",
            "type": "float"
        },
        {
            "name": "default",
            "type": "float"
        },
        {
            "name": "page",
            "type": "string",
            "description": "The sandbox option to add the option to. Can be a custom page."
        },
        {
            "name": "translation",
            "type": "string",
            "description": "The translation key for the option's name."
        }
    ]
}
